import type { 
  User, 
  Maquinaria, 
  OrdenTrabajo, 
  Repuesto, 
  HistorialMantenimiento, 
  Proveedor, 
  Notificacion 
} from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'usr-001',
    nombre: 'Juan Operador',
    email: 'operador@sistema.com',
    password: 'operador123',
    rol: 'Operador',
  },
  {
    id: 'usr-002',
    nombre: 'María Analista',
    email: 'analista@sistema.com',
    password: 'analista123',
    rol: 'Analista',
  },
  {
    id: 'usr-003',
    nombre: 'Carlos Coordinador',
    email: 'coordinador@sistema.com',
    password: 'coordinador123',
    rol: 'Coordinador',
  },
  {
    id: 'usr-004',
    nombre: 'Ana Gerente',
    email: 'gerencia@sistema.com',
    password: 'gerencia123',
    rol: 'Gerencia',
  },
];

export const MOCK_MAQUINARIA: Maquinaria[] = [
  {
    id: 'maq-001',
    nombre: 'Excavadora CAT 320',
    codigo: 'EXC-001',
    modelo: '320 GC',
    fabricante: 'Caterpillar',
    fechaAdquisicion: '2020-03-15',
    estado: 'Operativo',
    horometroActual: 4250,
    proximoMantenimiento: '2025-11-15',
    ubicacion: 'Zona Norte',
    horasOperacion: 4250,
    disponibilidad: 94.5,
    imagenUrl: 'https://images.unsplash.com/photo-1581094271901-8022df4466f9?w=800',
  },
  {
    id: 'maq-002',
    nombre: 'Bulldozer D6T',
    codigo: 'BUL-002',
    modelo: 'D6T LGP',
    fabricante: 'Caterpillar',
    fechaAdquisicion: '2019-08-22',
    estado: 'En Mantenimiento',
    horometroActual: 5890,
    proximoMantenimiento: '2025-11-20',
    ubicacion: 'Zona Sur',
    horasOperacion: 5890,
    disponibilidad: 87.2,
    imagenUrl: 'https://images.unsplash.com/photo-1581093458791-9d42e4e6e19e?w=800',
  },
  {
    id: 'maq-003',
    nombre: 'Tractor Agrícola 5055E',
    codigo: 'TRC-003',
    modelo: '5055E',
    fabricante: 'John Deere',
    fechaAdquisicion: '2021-01-10',
    estado: 'Operativo',
    horometroActual: 3120,
    proximoMantenimiento: '2025-11-25',
    ubicacion: 'Zona Este',
    horasOperacion: 3120,
    disponibilidad: 96.8,
    imagenUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
  },
  {
    id: 'maq-004',
    nombre: 'Cargadora 950M',
    codigo: 'CAR-004',
    modelo: '950M',
    fabricante: 'Caterpillar',
    fechaAdquisicion: '2020-11-05',
    estado: 'Averiado',
    horometroActual: 4780,
    proximoMantenimiento: '2025-11-10',
    ubicacion: 'Zona Oeste',
    horasOperacion: 4780,
    disponibilidad: 72.3,
    imagenUrl: 'https://images.unsplash.com/photo-1581093588401-fbb62ff0c3b5?w=800',
  },
  {
    id: 'maq-005',
    nombre: 'Retroexcavadora 420F',
    codigo: 'RTR-005',
    modelo: '420F',
    fabricante: 'Caterpillar',
    fechaAdquisicion: '2022-05-18',
    estado: 'Operativo',
    horometroActual: 1890,
    proximoMantenimiento: '2025-12-01',
    ubicacion: 'Zona Centro',
    horasOperacion: 1890,
    disponibilidad: 98.1,
    imagenUrl: 'https://images.unsplash.com/photo-1581093450021-4a7360e9a6b5?w=800',
  },
  {
    id: 'maq-006',
    nombre: 'Grúa Telescópica RT780',
    codigo: 'GRU-006',
    modelo: 'RT780',
    fabricante: 'Terex',
    fechaAdquisicion: '2019-12-08',
    estado: 'Operativo',
    horometroActual: 6340,
    proximoMantenimiento: '2025-11-12',
    ubicacion: 'Zona Norte',
    horasOperacion: 6340,
    disponibilidad: 91.4,
    imagenUrl: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800',
  },
  {
    id: 'maq-007',
    nombre: 'Compactadora CS56',
    codigo: 'CMP-007',
    modelo: 'CS56',
    fabricante: 'Caterpillar',
    fechaAdquisicion: '2021-07-22',
    estado: 'Fuera de Servicio',
    horometroActual: 2560,
    proximoMantenimiento: '2025-11-18',
    ubicacion: 'Taller Central',
    horasOperacion: 2560,
    disponibilidad: 45.8,
    imagenUrl: 'https://images.unsplash.com/photo-1581093804475-577d72e38aa0?w=800',
  },
  {
    id: 'maq-008',
    nombre: 'Motoniveladora 140M',
    codigo: 'MTN-008',
    modelo: '140M',
    fabricante: 'Caterpillar',
    fechaAdquisicion: '2020-02-14',
    estado: 'Operativo',
    horometroActual: 4520,
    proximoMantenimiento: '2025-11-22',
    ubicacion: 'Zona Sur',
    horasOperacion: 4520,
    disponibilidad: 93.7,
    imagenUrl: 'https://images.unsplash.com/photo-1581093458791-9d42e4e6e19e?w=800',
  },
];

export const MOCK_ORDENES_TRABAJO: OrdenTrabajo[] = [
  {
    id: 'ot-1001',
    maquinariaId: 'maq-002',
    maquinariaNombre: 'Bulldozer D6T',
    tipo: 'Preventivo',
    descripcionProblema: 'Mantenimiento preventivo de 500 horas',
    descripcionTrabajo: 'Cambio de aceite, filtros, revisión de sistemas hidráulicos',
    estado: 'En Progreso',
    prioridad: 'Media',
    fechaCreacion: '2025-10-25',
    tecnicoAsignado: 'Pedro Técnico',
    costoEstimado: 850,
    tiempoEstimado: 6,
  },
  {
    id: 'ot-1002',
    maquinariaId: 'maq-004',
    maquinariaNombre: 'Cargadora 950M',
    tipo: 'Correctivo',
    descripcionProblema: 'Falla en sistema hidráulico - pérdida de presión',
    estado: 'Abierta',
    prioridad: 'Alta',
    fechaCreacion: '2025-10-30',
    tecnicoAsignado: 'Luis Méndez',
    costoEstimado: 1250,
    tiempoEstimado: 8,
  },
  {
    id: 'ot-1003',
    maquinariaId: 'maq-001',
    maquinariaNombre: 'Excavadora CAT 320',
    tipo: 'Preventivo',
    descripcionProblema: 'Inspección programada - 4000 horas',
    descripcionTrabajo: 'Inspección completa de motor, transmisión y sistemas',
    estado: 'Cerrada',
    prioridad: 'Media',
    fechaCreacion: '2025-10-15',
    fechaCierre: '2025-10-18',
    tecnicoAsignado: 'Pedro Técnico',
    costoEstimado: 650,
    costoReal: 680,
    tiempoEstimado: 4,
    tiempoReal: 4.5,
  },
  {
    id: 'ot-1004',
    maquinariaId: 'maq-007',
    maquinariaNombre: 'Compactadora CS56',
    tipo: 'Correctivo',
    descripcionProblema: 'Falla crítica en motor - no arranca',
    estado: 'Pendiente Repuesto',
    prioridad: 'Alta',
    fechaCreacion: '2025-10-28',
    tecnicoAsignado: 'Roberto Sánchez',
    costoEstimado: 3500,
    tiempoEstimado: 16,
  },
  {
    id: 'ot-1005',
    maquinariaId: 'maq-003',
    maquinariaNombre: 'Tractor Agrícola 5055E',
    tipo: 'Predictivo',
    descripcionProblema: 'Análisis de vibraciones indica posible falla en rodamientos',
    estado: 'Abierta',
    prioridad: 'Media',
    fechaCreacion: '2025-10-29',
    tecnicoAsignado: 'Ana Técnica',
    costoEstimado: 420,
    tiempoEstimado: 3,
  },
  {
    id: 'ot-1006',
    maquinariaId: 'maq-006',
    maquinariaNombre: 'Grúa Telescópica RT780',
    tipo: 'Preventivo',
    descripcionProblema: 'Mantenimiento programado mensual',
    estado: 'Abierta',
    prioridad: 'Baja',
    fechaCreacion: '2025-10-31',
    costoEstimado: 580,
    tiempoEstimado: 5,
  },
  {
    id: 'ot-1007',
    maquinariaId: 'maq-005',
    maquinariaNombre: 'Retroexcavadora 420F',
    tipo: 'Correctivo',
    descripcionProblema: 'Ruido anormal en transmisión',
    estado: 'En Progreso',
    prioridad: 'Alta',
    fechaCreacion: '2025-10-30',
    tecnicoAsignado: 'Luis Méndez',
    costoEstimado: 920,
    tiempoEstimado: 6,
  },
];

export const MOCK_REPUESTOS: Repuesto[] = [
  {
    id: 'rep-001',
    nombre: 'Filtro de Aceite Motor CAT',
    sku: 'FLT-OIL-001',
    stock: 25,
    stockMinimo: 10,
    ubicacion: 'Estante A-12',
    proveedorId: 'prv-001',
    proveedorNombre: 'Distribuidora CAT',
    precio: 45.50,
    categoria: 'Filtros',
  },
  {
    id: 'rep-002',
    nombre: 'Filtro Hidráulico HF35554',
    sku: 'FLT-HYD-002',
    stock: 8,
    stockMinimo: 15,
    ubicacion: 'Estante A-13',
    proveedorId: 'prv-001',
    proveedorNombre: 'Distribuidora CAT',
    precio: 78.90,
    categoria: 'Filtros',
  },
  {
    id: 'rep-003',
    nombre: 'Aceite Hidráulico 68 (20L)',
    sku: 'ACE-HYD-003',
    stock: 42,
    stockMinimo: 20,
    ubicacion: 'Zona Líquidos B-01',
    proveedorId: 'prv-002',
    proveedorNombre: 'Lubricantes Industriales SA',
    precio: 185.00,
    categoria: 'Lubricantes',
  },
  {
    id: 'rep-004',
    nombre: 'Rodamiento SKF 6310',
    sku: 'ROD-SKF-004',
    stock: 12,
    stockMinimo: 8,
    ubicacion: 'Estante C-05',
    proveedorId: 'prv-003',
    proveedorNombre: 'Rodamientos Técnicos',
    precio: 125.50,
    categoria: 'Rodamientos',
  },
  {
    id: 'rep-005',
    nombre: 'Batería 12V 180Ah',
    sku: 'BAT-12V-005',
    stock: 6,
    stockMinimo: 8,
    ubicacion: 'Estante D-02',
    proveedorId: 'prv-004',
    proveedorNombre: 'Baterías Power',
    precio: 320.00,
    categoria: 'Eléctricos',
  },
  {
    id: 'rep-006',
    nombre: 'Correa Serpentina Multi-V',
    sku: 'COR-MUL-006',
    stock: 18,
    stockMinimo: 12,
    ubicacion: 'Estante E-08',
    proveedorId: 'prv-005',
    proveedorNombre: 'Repuestos Universales',
    precio: 68.75,
    categoria: 'Correas',
  },
  {
    id: 'rep-007',
    nombre: 'Manguera Hidráulica 1/2" (5m)',
    sku: 'MAN-HYD-007',
    stock: 15,
    stockMinimo: 10,
    ubicacion: 'Estante F-03',
    proveedorId: 'prv-001',
    proveedorNombre: 'Distribuidora CAT',
    precio: 92.30,
    categoria: 'Mangueras',
  },
  {
    id: 'rep-008',
    nombre: 'Pastillas de Freno Delanteras',
    sku: 'FRE-PAS-008',
    stock: 4,
    stockMinimo: 10,
    ubicacion: 'Estante G-01',
    proveedorId: 'prv-005',
    proveedorNombre: 'Repuestos Universales',
    precio: 156.00,
    categoria: 'Frenos',
  },
  {
    id: 'rep-009',
    nombre: 'Sello Hidráulico 50x70x10',
    sku: 'SEL-HYD-009',
    stock: 28,
    stockMinimo: 15,
    ubicacion: 'Estante C-12',
    proveedorId: 'prv-003',
    proveedorNombre: 'Rodamientos Técnicos',
    precio: 32.50,
    categoria: 'Sellos',
  },
  {
    id: 'rep-010',
    nombre: 'Bomba de Combustible Eléctrica',
    sku: 'BOM-COM-010',
    stock: 3,
    stockMinimo: 5,
    ubicacion: 'Estante H-04',
    proveedorId: 'prv-001',
    proveedorNombre: 'Distribuidora CAT',
    precio: 485.00,
    categoria: 'Sistema Combustible',
  },
];

export const MOCK_HISTORIAL: HistorialMantenimiento[] = [
  {
    id: 'hist-001',
    ordenTrabajoId: 'ot-1003',
    maquinariaId: 'maq-001',
    fecha: '2025-10-18',
    detalles: 'Mantenimiento preventivo completado - Motor y sistemas OK',
    repuestosUsados: [
      { repuestoId: 'rep-001', repuestoNombre: 'Filtro de Aceite Motor CAT', cantidad: 2 },
      { repuestoId: 'rep-002', repuestoNombre: 'Filtro Hidráulico HF35554', cantidad: 1 },
      { repuestoId: 'rep-003', repuestoNombre: 'Aceite Hidráulico 68 (20L)', cantidad: 3 },
    ],
    costoTotal: 680,
    tiempoTotal: 4.5,
  },
  {
    id: 'hist-002',
    ordenTrabajoId: 'ot-999',
    maquinariaId: 'maq-001',
    fecha: '2025-09-15',
    detalles: 'Cambio de rodamientos en sistema de oruga',
    repuestosUsados: [
      { repuestoId: 'rep-004', repuestoNombre: 'Rodamiento SKF 6310', cantidad: 4 },
      { repuestoId: 'rep-009', repuestoNombre: 'Sello Hidráulico 50x70x10', cantidad: 8 },
    ],
    costoTotal: 762,
    tiempoTotal: 6,
  },
  {
    id: 'hist-003',
    ordenTrabajoId: 'ot-998',
    maquinariaId: 'maq-002',
    fecha: '2025-09-22',
    detalles: 'Reparación sistema eléctrico - reemplazo batería',
    repuestosUsados: [
      { repuestoId: 'rep-005', repuestoNombre: 'Batería 12V 180Ah', cantidad: 1 },
    ],
    costoTotal: 420,
    tiempoTotal: 2,
  },
  {
    id: 'hist-004',
    ordenTrabajoId: 'ot-997',
    maquinariaId: 'maq-003',
    fecha: '2025-10-05',
    detalles: 'Mantenimiento de 3000 horas - Servicio completo',
    repuestosUsados: [
      { repuestoId: 'rep-001', repuestoNombre: 'Filtro de Aceite Motor CAT', cantidad: 1 },
      { repuestoId: 'rep-006', repuestoNombre: 'Correa Serpentina Multi-V', cantidad: 1 },
      { repuestoId: 'rep-003', repuestoNombre: 'Aceite Hidráulico 68 (20L)', cantidad: 2 },
    ],
    costoTotal: 560,
    tiempoTotal: 5,
  },
];

export const MOCK_PROVEEDORES: Proveedor[] = [
  {
    id: 'prv-001',
    nombre: 'Distribuidora CAT',
    contacto: 'Jorge Martínez',
    telefono: '+56 2 2345 6789',
    email: 'contacto@distcat.cl',
    direccion: 'Av. Industrial 1250, Santiago',
    tiempoEntrega: 3,
  },
  {
    id: 'prv-002',
    nombre: 'Lubricantes Industriales SA',
    contacto: 'Patricia Silva',
    telefono: '+56 2 2456 7890',
    email: 'ventas@lubind.cl',
    direccion: 'Calle Los Aromos 567, Quilicura',
    tiempoEntrega: 2,
  },
  {
    id: 'prv-003',
    nombre: 'Rodamientos Técnicos',
    contacto: 'Miguel Rojas',
    telefono: '+56 2 2567 8901',
    email: 'info@rodtec.cl',
    direccion: 'Av. Matta 890, San Miguel',
    tiempoEntrega: 5,
  },
  {
    id: 'prv-004',
    nombre: 'Baterías Power',
    contacto: 'Carla Fuentes',
    telefono: '+56 2 2678 9012',
    email: 'ventas@batpower.cl',
    direccion: 'Los Alerces 234, Maipú',
    tiempoEntrega: 1,
  },
  {
    id: 'prv-005',
    nombre: 'Repuestos Universales',
    contacto: 'Daniel Pérez',
    telefono: '+56 2 2789 0123',
    email: 'contacto@repuniv.cl',
    direccion: 'Gran Avenida 4567, San Bernardo',
    tiempoEntrega: 4,
  },
];

export const MOCK_NOTIFICACIONES: Notificacion[] = [
  {
    id: 'not-001',
    tipo: 'alerta',
    titulo: 'Stock Crítico',
    mensaje: 'Filtro Hidráulico HF35554 por debajo del stock mínimo (8/15)',
    fecha: '2025-10-31T10:30:00',
    leida: false,
    enlace: '/inventory/rep-002',
  },
  {
    id: 'not-002',
    tipo: 'warning',
    titulo: 'Mantenimiento Próximo',
    mensaje: 'Excavadora CAT 320 requiere mantenimiento en 5 días',
    fecha: '2025-10-31T09:15:00',
    leida: false,
    enlace: '/machinery/maq-001',
  },
  {
    id: 'not-003',
    tipo: 'alerta',
    titulo: 'Nueva Incidencia',
    mensaje: 'Operador reportó falla en Bulldozer D6T',
    fecha: '2025-10-30T16:45:00',
    leida: true,
    enlace: '/work-orders/ot-1001',
  },
  {
    id: 'not-004',
    tipo: 'alerta',
    titulo: 'Stock Bajo',
    mensaje: 'Pastillas de Freno Delanteras por debajo del mínimo (4/10)',
    fecha: '2025-10-30T14:20:00',
    leida: false,
    enlace: '/inventory/rep-008',
  },
  {
    id: 'not-005',
    tipo: 'success',
    titulo: 'OT Completada',
    mensaje: 'Orden de Trabajo OT-1003 cerrada exitosamente',
    fecha: '2025-10-30T11:00:00',
    leida: true,
  },
  {
    id: 'not-006',
    tipo: 'warning',
    titulo: 'Máquina Fuera de Servicio',
    mensaje: 'Compactadora CS56 requiere atención urgente',
    fecha: '2025-10-29T08:30:00',
    leida: true,
    enlace: '/machinery/maq-007',
  },
  {
    id: 'not-007',
    tipo: 'alerta',
    titulo: 'Stock Crítico',
    mensaje: 'Bomba de Combustible Eléctrica por debajo del mínimo (3/5)',
    fecha: '2025-10-29T07:15:00',
    leida: false,
    enlace: '/inventory/rep-010',
  },
  {
    id: 'not-008',
    tipo: 'info',
    titulo: 'Nuevo Repuesto Registrado',
    mensaje: 'Se agregó un nuevo tipo de filtro al inventario',
    fecha: '2025-10-28T15:00:00',
    leida: true,
  },
];
